# Use containers instead of full VMs for faster startup.
sudo: false

language: python
python:
    - 3.6

cache: pip

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-package=dfa

after_success:
    - coveralls
    
